.TH cif-drop 1 "2020-11-23" "version 1.0.1" "User Commands"
.if n .ad l
.nh
.SH NAME
cif\-drop \- A tool to drop columns from mmCIF files
.SH SYNOPSIS
cif\-drop [OPTION] file1 [file2..]
.SH DESCRIPTION
This tool makes it easy to drop a single column from a category
in mmCIF files.
.SH OPTIONS
.TP
\fB--output\fR=<file>, \fB-o\fR <file>
Write output to \fI<file>\fR, default is \fIstdout\fR.
.TP
\fB--column\fR=<name>, \fB-c\fR <name>
Colunn to drop, should be of the form \fB'_category.item'\fR with the leading
underscore. Can be specified multiple times.
.TP
\fB--verbose\fR,\fB-v\fR
Be more verbose, useful to diagnose validation errors.
.SH AUTHOR
Written by Maarten L. Hekkelman <maarten@hekkelman.com>
.SH "REPORTING BUGS"
Report bugs at https://github.com/PDB-REDO/cif-tools/issues
.SH "SEE ALSO"
\fBcif-diff\fR, \fBcif-grep\fR, \fBcif-merge\fR, \fBcif-validate\fR, 
\fBcif2pdb\fR, \fBmmCQL\fR, \fBpdb2cif\fR.
