.TH pdb2cif 1 "2020-11-23" "version 1.0.1" "User Commands"
.if n .ad l
.nh
.SH NAME
pdb2cif \- Convert the content of a PDB file into mmCIF format
.SH SYNOPSIS
pdb2cif [OPTION] input [output]
.SH DESCRIPTION
This tools attempts to write out the contents of a PDB file in mmCIF format.
.sp
The conversion of a PDB file into mmCIF format is not trivial. The numbering
schemes differ and in some cases it is even necessary to do a sequence
alignment to recover correct sequence numbers.
.sp
When \fBCCP4\fR is installed and sourced correctly, this tool will use the
information in the \fBCCP4\fR monomers library to guide the construction of
a correct mmCIF file. In the absence of \fBCCP4\fR a best effort is done.
.SH OPTIONS
If no output file is given, the result is printed to /fIstdout\fR.
Both input and output files can be compressed.
.TP
\fB--dict\fR=<file>
Specify a dictionary file containing restraints for residues specific to
this file.
.TP
\fB--validate\fR
Validate the file before writing the output.
.TP
\fB--verbose\fR,\fB-V\fR
Be more verbose, useful to diagnose validation errors.
.SH AUTHOR
Written by Maarten L. Hekkelman <maarten@hekkelman.com>
.SH "REPORTING BUGS"
Report bugs at https://github.com/PDB-REDO/cif-tools/issues
.SH "SEE ALSO"
\fBcif-diff\fR, \fBcif-drop\fR, \fBcif-grep\fR, \fBcif-merge\fR, 
\fBcif-validate\fR, \fBcif2pdb\fR, \fBmmCQL\fR.
